# Generated by Django 2.2.1 on 2019-05-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Signup', '0001_initial'),
        ('PaymentInformation', '0001_initial'),
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signup.Members')),
                ('card_information_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentInformation.CreditCard')),
                ('real_estate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.RealEstates')),
            ],
        ),
    ]
