# Generated by Django 2.2.1 on 2019-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
    ]
